[tool.poetry]
name = "ai-assistant"
version = "0.1.0"
description = ""
authors = ["Gerard Church <gerardchurch133@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.44.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
